# Generated by Django 3.0.6 on 2020-05-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogtagindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
    ]
