# Generated by Django 3.0.6 on 2020-05-18 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_blogtagcategorypage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTagCategoryPage',
            new_name='BlogCategoryIndexPage',
        ),
    ]
