# Generated by Django 3.0.6 on 2020-05-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0012_auto_20200518_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
