# Generated by Django 3.0.6 on 2020-05-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0013_delete_blogtagindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategoryIndexPage',
        ),
    ]
