# Generated by Django 3.0.6 on 2020-05-19 15:16

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_blogcategoryindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggeditems', to='blog.BlogPage'),
        ),
    ]
