# Generated by Django 3.0.6 on 2020-05-24 13:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200524_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('para', wagtail.core.blocks.RichTextBlock(blank=True)), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS'), ('json', 'JSON')])), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('syntax', 'default'), ('emacs', 'emacs'), ('monokai', 'monokai'), ('vim', 'vim'), ('xcode', 'xcode')])), ('code', wagtail.core.blocks.TextBlock())]))]),
        ),
    ]
