# Generated by Django 3.0.6 on 2020-05-24 21:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200524_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('para', wagtail.core.blocks.RichTextBlock(blank=True)), ('code', wagtail.core.blocks.StructBlock([('lang', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS'), ('json', 'JSON')])), ('src', wagtail.core.blocks.TextBlock())]))]),
        ),
    ]
