# Generated by Django 3.0.6 on 2020-05-31 08:34

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200526_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='appname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='apps',
            field=wagtail.core.fields.StreamField([('inputs', wagtail.core.blocks.StructBlock([('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('Image', 'image'), ('Text', 'text'), ('Video', 'video'), ('Excel', 'excel'), ('CSV', 'csv')]))])), ('outputs', wagtail.core.blocks.StructBlock([('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('Image', 'image'), ('Text', 'text'), ('Video', 'video'), ('Excel', 'excel'), ('CSV', 'csv')]))]))], null=True),
        ),
    ]
