# Generated by Django 3.0.6 on 2020-05-31 08:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200531_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='apps',
            field=wagtail.core.fields.StreamField([('inputs', wagtail.core.blocks.StructBlock([('file_name', wagtail.core.blocks.CharBlock(max_length=100)), ('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('Image', 'image'), ('Text', 'text'), ('Video', 'video'), ('Excel', 'excel'), ('CSV', 'csv')]))])), ('outputs', wagtail.core.blocks.StructBlock([('file_name', wagtail.core.blocks.CharBlock(max_length=100)), ('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('Image', 'image'), ('Text', 'text'), ('Video', 'video'), ('Excel', 'excel'), ('CSV', 'csv')]))]))], null=True),
        ),
    ]
