# Generated by Django 3.0.6 on 2020-06-22 22:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200531_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='apps',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='files',
            field=wagtail.core.fields.StreamField([('entry', wagtail.core.blocks.StructBlock([('entry', wagtail.core.blocks.ChoiceBlock(choices=[('Input', 'input'), ('Output', 'output')])), ('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('Image', 'image'), ('Text', 'text'), ('Video', 'video'), ('Excel', 'excel'), ('CSV', 'csv')])), ('file_id', wagtail.core.blocks.IntegerBlock())]))], null=True),
        ),
    ]
