# Generated by Django 3.0.6 on 2020-06-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200622_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='files',
            new_name='apps',
        ),
    ]
