# Generated by Django 3.0.6 on 2020-06-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200622_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='apps',
            new_name='file_description',
        ),
    ]
