# Generated by Django 3.0.6 on 2020-06-22 22:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20200622_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='file_description',
            field=wagtail.core.fields.StreamField([('file', wagtail.core.blocks.StructBlock([('input_or_output', wagtail.core.blocks.ChoiceBlock(choices=[('Input', 'input'), ('Output', 'output')])), ('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('Image', 'image'), ('Text', 'text'), ('Video', 'video'), ('Excel', 'excel'), ('CSV', 'csv')])), ('file_id', wagtail.core.blocks.IntegerBlock())]))], null=True),
        ),
    ]
