# Generated by Django 3.0.6 on 2020-06-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200622_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='file_description',
            new_name='app_form',
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='appname',
            new_name='app_name',
        ),
    ]
