# Generated by Django 3.0.6 on 2020-06-22 22:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20200622_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='app_form',
            field=wagtail.core.fields.StreamField([('input', wagtail.core.blocks.StructBlock([('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('excel', 'Excel'), ('csv', 'CSV')])), ('file_id', wagtail.core.blocks.IntegerBlock())])), ('output', wagtail.core.blocks.StructBlock([('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('excel', 'Excel'), ('csv', 'CSV')])), ('file_id', wagtail.core.blocks.IntegerBlock())]))], null=True),
        ),
    ]
