# Generated by Django 3.0.6 on 2020-06-22 22:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20200622_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='app_form',
            field=wagtail.core.fields.StreamField([('input', wagtail.core.blocks.StructBlock([('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('Image', 'image'), ('Text', 'text'), ('Video', 'video'), ('Excel', 'excel'), ('CSV', 'csv')])), ('file_id', wagtail.core.blocks.IntegerBlock())])), ('output', wagtail.core.blocks.StructBlock([('file_type', wagtail.core.blocks.ChoiceBlock(choices=[('Image', 'image'), ('Text', 'text'), ('Video', 'video'), ('Excel', 'excel'), ('CSV', 'csv')])), ('file_id', wagtail.core.blocks.IntegerBlock())]))], null=True),
        ),
    ]
