# Generated by Django 3.0.6 on 2020-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
