# Generated by Django 3.0.6 on 2020-05-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='url',
        ),
    ]
